### ISSUE TITLE
Cannot Process the Raw Data

### ISSUE THREAD

**Issue by SophieSarceau** [LirongWu/MAPE-PPI#4]
When I use the command: "python data_process.py --dataset SHS27k" to pre=process the raw data, there occurs and error,
![image](https://github.com/LirongWu/MAPE-PPI/assets/46676385/dff555e4-c3fc-4e66-8424-8adf7453e7b5)

I wonder if the processing file is the right version. Thanks for your notice and really appreciate your work.

**Comment by LirongWu** [comment]
The processing file is the correct version to run on my site. I noticed that this error may be due to the latest version of numpy discarding this usage. 

As per the official instructions, _"If you meant to do this, you must specify 'dtype=object' when creating the ndarray"_. Following this hint, we can solve this problem.

**Comment by SophieSarceau** [comment]
Thanks, Lirong.
We can use the following code to pre-process the raw data.
```
r_edge_list = np.array(r_edge_list, dtype=object)
k_edge_list = np.array(k_edge_list, dtype=object)
np.save("../processed_data/protein.rball.edges.{}.npy".format(dataset), r_edge_list, allow_pickle=True)
np.save("../processed_data/protein.knn.edges.{}.npy".format(dataset), k_edge_list, allow_pickle=True)
```
